using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace speedDials2ccs
{
    class CCSBuilder
    {
        public void build(string fileName, List<XUser> users)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("# Generated by phoneBook2ccs tool from old IPTC\n");
            sb.Append("# Import this contents into CCS node /names/numbers/ in IPTC-K\n");
            foreach (XUser user in users)
            {
                sb.Append(user.Number + "\n");
                sb.Append(" name " + user.LastName + user.FirstName + "\n");
                sb.Append(" protected " + user.IsProtected.ToString().ToLower() + "\n");
                sb.Append("!\n");
            }
            System.IO.File.WriteAllText(fileName, sb.ToString());
        }
    }
}
