using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.IO;

namespace speedDials2ccs
{
    class CCSBuilder
    {
        StringBuilder sb = new StringBuilder();

        public void build(XDocument nodes, string outputFile)
        {
            sb.Append("# Generated by speedDial2ccs tool from old IPTC\n");
            sb.Append("# Import this contents into CCS node /layout in IPTC-K\n");
            sb.Append("# This file contains only AUT and MB tabs!\n");
            Process(nodes.Root, 0);
            File.WriteAllText(outputFile, sb.ToString());
        }

        void Process(XElement element, int depth)
        {
            // For simplicity, argument validation not performed

            if (!element.HasElements)
            {
                sb.Append
                (
                    string.Format
                    (
                        "{0}{1} {2}\t# {1}\n",
                        "".PadLeft(depth, ' '), // {0}
                        element.Name.LocalName,  // {1}
                        element.Value            // {2}
                    )
                );
            }
            else
            {
                sb.Append
                (
                    "".PadLeft(depth, ' ') + // Indent to show depth
                    element.Name.LocalName + "\n"
                );

                depth++;

                foreach (XElement child in element.Elements())
                {
                    Process(child, depth);
                }

                depth--;

                sb.Append
                (
                    "".PadLeft(depth, ' ') + // Indent to show depth
                    "!\n"
                );
            }
        }
    }
}
